### ISSUE TITLE
Browser navigation and new page trigger

### ISSUE THREAD

**Issue by zoran-cuckovic** [DataVizForAll/leaflet-storymaps-with-google-sheets#91]
Your story-map template is excellent ! However, I've noticed that it tends to register every move that the user makes as a new web page. Eventually, I'm unable to use my browser to navigate back from the demo (Figure). Same thing in Chrome and Mozilla. Do you have an idea how to prevent this behaviour ?
Thanks !
![image](https://user-images.githubusercontent.com/6622934/184962083-b59af529-8dac-436d-9009-75f464da7a5e.png)

**Comment by ilyankou** [comment]
Hi @zoran-cuckovic 

Thank you for sharing this interesting observation - this is something that never came up before. We are using [URL hash](https://developer.mozilla.org/en-US/docs/Web/API/URL/hash) to navigate between chapters; this is done to enable users to share links to specific chapters (eg [this link](https://handsondataviz.github.io/leaflet-storymaps-with-google-sheets/#6) will automatically scroll to chapter 6). While in principle it may be possible to use some other URL elements (eg  `?` instead of `#` to pass chapters as arguments), logically our current hashing/anchoring makes sense and I'm inclined to keep it, at least for now.

**Comment by zoran-cuckovic** [comment]
Thanks @ilyankou !
I've suspended this behaviour by commenting out the line 293 of the javascipt file: 
https://github.com/HandsOnDataViz/leaflet-storymaps-with-google-sheets/blob/44912cd10078213e88d657bc5ef48586877ce360/scripts/storymap.js#L293
Not elegant, but simple enough.
